base:
  project: creditcardfraud-project
  random_state: 42
  target_col: Class

data_source:
  s3_source: data_given/creditcard.csv

load_data:
  raw_dataset_csv: data/raw/creditcard.csv

split_data:
  train_path: data/processed/train_creditcard.csv
  test_path: data/processed/test_creditcard.csv
  test_size: 0.2


estimators:
  LogisticRegression:
    params:
      # C: 0.1
      # max_iter: 200
      # solver: 'liblinear'
      C: 0.2
      max_iter: 300
      solver: 'liblinear'
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib
